### ISSUE TITLE
请问如何构建支持mac M1的包呢？

### ISSUE THREAD

**Issue by zhangyuge** [eycorsican/xleaf#2]
你好，使用cargo build -p leaf-ffi --release打出来的包只支持x86，请问怎么构建同时支持x86和arm64的osx包呢？

**Comment by zhangyuge** [comment]
使用cargo lipo --targets aarch64-apple-darwin x86_64-apple-darwin --manifest-path leaf-ffi/Cargo.toml 构建了x86和arm64再合并，能使用。请指教这样是打包出来否有潜在问题没注意到的呢？

**Comment by alsojin0806** [comment]
make lib 感觉应该可以的
